version: '3'
services:
#  db:
#    restart: always
#    image: postgres:15.1
#    environment:
#      - POSTGRES_USER=${DATABASE_USER}
#      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
#      - POSTGRES_DB=${DATABASE_NAME}
#    volumes:
#      - ./postgres-data/postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
  app:
    restart: always
    build: .
    environment:
      - DATABASE_URL=sqlite:///./db.sqlite
    command: bash -c "alembic upgrade head && uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - .:/app